const en = `# AML & KYC

With the aim of policy, money laundering is typically defined as the actions aimed at concealing or disguising the true origin of criminally obtained income, making illegally obtained proceeds appear as if they stem from legitimate sources or are legitimate assets. Money laundering typically occurs in three stages. Cash initially enters the financial system at the "placement" stage, where funds obtained from criminal activity are converted into monetary instruments such as money orders or traveler's checks, or deposited into accounts at financial institutions. At the "layering" stage, funds are transferred or moved to other accounts or financial institutions to further separate the money from its criminal origin. At the "integration" stage, funds are reintroduced into the economy and used to purchase legitimate assets or finance other criminal activities or legitimate businesses. Financing terrorism may not involve proceeds from criminal activity but rather an attempt to conceal the origin or intended use of funds, which will later be used for criminal purposes. All business units and locations within Global Investment will collaborate to create a unified effort to combat money laundering. Each business unit and location has implemented risk-based procedures expected to prevent, detect, and report transactions. All efforts expended will be documented and preserved. The "Know Your Customer" policy has become particularly significant globally, especially among banks and other financial institutions, aiming to prevent identity theft, money laundering, financial fraud, and terrorist activities. Global Investment has a zero-tolerance policy towards fraud and takes all possible measures to prevent it. Any fraudulent activity will be documented, and all associated accounts will be immediately closed. All funds in these accounts will be confiscated.

Prevention: Global Investment aims to ensure the integrity of any confidential data it receives, such as information about your account and transactions, using various security measures and fraud controls. Ensuring the security of your electronic transactions requires us to obtain certain data from you, including your chosen method of deposit. When you deposit funds, we will require the following documents:

- A copy of your valid passport with the signature page
- Copies of your credit cards used for depositing (front side showing only the last 4 digits, back side with CVV covered)
- A copy of a recent utility bill in your name and address
- Signed history of your online transaction purchases

If you have any questions, please feel free to contact our support service: **support@gl-investment.pl**. When do I need to provide these documents? We highly appreciate you taking the time to provide us with all the necessary documents as quickly as possible to avoid any delays in processing your transactions. We require receipt of all necessary documents before carrying out any monetary transactions on your behalf. In some cases, we may need to request these documents before allowing any other actions on your account, such as deposits or agreements. Please note that if we do not receive the required documents on file, your pending withdrawals will be canceled and credited back to your trading account. We will notify you of such an event through our system. How can I send you these documents? Please scan your documents or take high-quality photos using a digital camera, save the images in jpeg format, and then send them to us at **support@gl-investment.pl**. How can I be sure that my documents are safe with you? Global Investment prioritizes document security and handles all documents it receives with the utmost respect and confidentiality. All files we receive are fully protected using the highest level of encryption at each stage of the review process. We thank you for your cooperation in helping to make Global Investment a safer place for trading.
`;

const pl = `# AML & KYC

W celu polityki, pranie brudnych pieniędzy zazwyczaj jest definiowane jako działania mające na celu ukrycie lub zamaskowanie prawdziwego pochodzenia dochodów uzyskanych w sposób przestępczy, sprawiając, że nielegalnie uzyskane środki wyglądają tak, jakby pochodziły z legalnych źródeł lub były legalnymi aktywami. Pranie pieniędzy zazwyczaj występuje na trzech etapach. Gotówka początkowo wchodzi do systemu finansowego na etapie "umiejscowienia", gdzie środki uzyskane z działalności przestępczej są przekształcane w instrumenty pieniężne, takie jak przekazy pieniężne lub czeki podróżnych, lub są deponowane na kontach w instytucjach finansowych. Na etapie "warstwowania", środki są przekazywane lub przenoszone na inne konta lub instytucje finansowe, aby dalej oddzielić pieniądze od ich przestępczego pochodzenia. Na etapie "integracji", środki są ponownie wprowadzane do gospodarki i używane do zakupu legalnych aktywów lub finansowania innych działalności przestępczych lub legalnych przedsiębiorstw. Finansowanie terroryzmu może nie obejmować dochodów z działalności przestępczej, ale raczej próbę ukrycia pochodzenia lub zamierzonego wykorzystania środków, które później zostaną wykorzystane do celów przestępczych. Wszystkie jednostki biznesowe i lokalizacje w ramach Global Investment będą współpracować, aby stworzyć zjednoczone wysiłki w zwalczaniu prania pieniędzy. Każda jednostka biznesowa i lokalizacja wdrożyła procedury oparte na ryzyku, których celem jest zapobieganie, wykrywanie i zgłaszanie transakcji. Wszelkie wydatki zostaną udokumentowane i zachowane. Polityka "Znaj swojego klienta" stała się szczególnie istotna na całym świecie, zwłaszcza wśród banków i innych instytucji finansowych, mając na celu zapobieganie kradzieży tożsamości, praniu pieniędzy, oszustwom finansowym i działaniom terrorystycznym. Global Investment ma politykę zerowej tolerancji wobec oszustw i podejmuje wszelkie możliwe środki w celu ich zapobiegania. Każda działalność oszustwa będzie udokumentowana, a wszystkie powiązane konta zostaną natychmiast zamknięte. Wszystkie środki na tych kontach zostaną skonfiskowane.

Zapobieganie: Global Investment ma na celu zapewnienie integralności wszelkich poufnych danych, jakie otrzymuje, takich jak informacje o Twoim koncie i transakcjach, przy użyciu różnych środków bezpieczeństwa i kontroli nad oszustwami. Zapewnienie bezpieczeństwa Twoich transakcji elektronicznych wymaga od nas uzyskania pewnych danych od Ciebie, w tym Twojego wybranego sposobu wpłaty. Gdy wpłacasz środki, będziemy wymagać następujących dokumentów:

- Kopii Twojego ważnego paszportu z podpisaną stroną
- Kopii używanych przez Ciebie kart kredytowych do wpłat (tylko przednia strona z ostatnimi 4 cyframi, tylna strona z zasłoniętym CVV)
- Kopii ostatniego rachunku za media na Twoje nazwisko i adres
- Podpisanej historii Twoich zakupów online

Jeśli masz jakiekolwiek pytania, prosimy o kontakt z naszym działem obsługi: **support@gl-investment.pl**. Kiedy muszę dostarczyć te dokumenty? Bardzo doceniamy Twój czas poświęcony na dostarczenie nam wszystkich niezbędnych dokumentów tak szybko, jak to możliwe, aby uniknąć opóźnień w przetwarzaniu Twoich transakcji. Wymagamy otrzymania wszystkich niezbędnych dokumentów przed przeprowadzeniem jakichkolwiek transakcji pieniężnych w Twoim imieniu. W niektórych przypadkach możemy poprosić o te dokumenty przed zezwoleniem na jakiekolwiek inne działania na Twoim koncie, takie jak wpłaty lub umowy. Prosimy zauważyć, że jeśli nie otrzymamy wymaganych dokumentów, twoje oczekujące wypłaty zostaną anulowane i zaksięgowane z powrotem na Twoim koncie handlowym. Powiadomimy Cię o takim zdarzeniu za pośrednictwem naszego systemu. Jak mogę przesłać Ci te dokumenty? Proszę zeskanować swoje dokumenty lub zrobić wysokiej jakości zdjęcia za pomocą aparatu cyfrowego, zapisać obrazy w formacie jpeg, a następnie przesłać je do nas pod adres **support@gl-investment.pl**. Jak mogę być pewien, że moje dokumenty są u Ciebie bezpieczne? Global Investment priorytetowo traktuje bezpieczeństwo dokumentów i traktuje wszystkie otrzymane dokumenty z najwyższym szacunkiem i poufnością. Wszystkie pliki, które otrzymujemy, są w pełni chronione przy użyciu najwyższego poziomu szyfrowania na każdym etapie procesu recenzji. Dziękujemy za współpracę w sprawie uczynienia Global Investment bezpieczniejszym miejscem do handlu.
`;

const res: { [key: string]: string } = {
  en,
  pl,
};

export default res;
