import { unstable_setRequestLocale } from "next-intl/server";

import LayoutPolicy from "@/layouts/policy";

import content from "./data";

export type RiskDisclosureParams = Readonly<{
  params: {
    locale: string;
  };
}>;

export default function RiskDisclosure({ params }: RiskDisclosureParams) {
  unstable_setRequestLocale(params.locale);

  return <LayoutPolicy content={content[params.locale]} />;
}

// const content = `# Risk Disclosure

// ## Introduction

// The company is required to categorize Clients as either (a) Retail, (b) Professional Or (c) Eligible Counterparties.

// ## General

// Every type of Financial Instrument has its own characteristics and entails different risks depending on the nature of each investment. A general description of the nature and the risks of financial instruments is summarized below. However, this document does NOT disclose all the associated risks or other important aspects of the Financial Instruments and it should NOT be considered as investment advice or recommendation for the provision of any service or

// ## Investment Risks

// a. Market Risk: is the risk that the value of a portfolio will decrease due to the change in value of the market factors such as stock prices, interest rates, exchange rates and commodity prices. In case of a negative fluctuation in prices, investors in financial instruments run the risk of losing part or all of their invested capital.

// b. Systemic Risk: is the risk of collapse of the entire market or the entire financial system. It refers to the risks imposed by interdependencies in a system or market, where the failure of a single entity or cluster of entities can cause a cascading failure, which could potentially bring down the entire system or market.

// c. Credit Risk: is the risk of a borrower’s failure to repay a loan or otherwise meet a contractual obligation (i.e. failure to pay interest to bond holders). Credit risk is closely tied to the potential return of an investment, the most notable being that the yields on bonds correlate strongly to their perceived credit risk.

// d. Settlement Risk: is the risk that a counterparty does not deliver a security or its value in cash per agreement when the security was traded after the other counterparty or counterparties have already delivered security or cash value per the trade agreement. This risk is limited where the investment involves financial instruments traded in regulated markets because of the regulation of such markets. This risk increases in case the investment involves financial instruments traded outside regulated markets or where their settlement takes place in different time zones or different clearing systems.

// e. Liquidity Risk: is the risk stemming from the lack of marketability of an investment that cannot be bought or sold quickly enough to prevent or minimize a loss. Liquidity risk becomes particularly important to investors who are about to hold or currently hold an asset, since it affects their ability to trade.

// f. Operational Risk: is the risk of business operations failing due to human error. Operational risk will change from industry to industry, and is an important consideration to make when looking at potential investment decisions. Industries with lower human interaction are likely to have lower operational risk.

// g. Political Risk: is the risk that an investment’s returns could suffer as a result of political changes or instability in a country. Instability affecting investment returns could stem from a change in government, legislative bodies, other foreign policy makers, or military control.

// ## Financial Instruments and related Risks

// a. Stocks/Shares: represent ownership in the share capital of a company. Investors are exposed to all major risks mentioned in section 3 above and in particular to market risk. It must be emphasized that there are no guarantees when it comes to individual stocks. Some companies pay out dividends, but many others do not. Without dividends, an investor can make profit on a stock only through its price appreciation in the open market. On the downside, in case of the company’s insolvency, the investor may lose the entire value of his investment.

// b. Warrants: companies will often include warrants as part of a new‐issue offering to entice investors into buying the new security. A warrant is like an option. It gives the holder the right but not the obligation to buy an underlying security at a certain price, quantity and future time. It is unlike an option in that a warrant is issued by a company, whereas an option is an instrument of the stock exchange. The Warrant is invariably limited in time, with the consequence that if the investor does not exercise or sell the Warrant within the pre‐determined timescale, the Warrant expires with no value. Warrants provide leverage, the extent of which depends on the Warrant’s exercise price relative to the price of the underlying security. Therefore, a relatively small fluctuation in the price of the underlying security may lead to a disproportionately larger fluctuation, favourable or unfavourable, to the price of the Warrant. The price of Warrants can therefore be very volatile. Before the purchase of a Warrant, the investor must be aware that there is a risk of losing the whole amount of his investment as well as any commissions and costs incurred. Warrants are subject to all of the major risks mentioned in section 3.

// c. Rights: a security giving stockholders entitlement to purchase new shares issued by the corporation at a predetermined price (normally less than the current market price) in proportion to the number of shares already owned. Rights are issued only for a short period of time, after which they expire. If the Right is exercised, its holder is required to pay to the issuer the exercise price. The exercise of the Right will give its holder all the rights and risks of ownership of the underlying security. Rights provide leverage, the extent of which depends on the Right’s exercise price relative to the price of the underlying security. Therefore, a relatively small fluctuation in the price of the underlying security may lead to a disproportionately larger fluctuation, favourable or unfavourable, to the price of the Right. The price of Rights can therefore be very volatile. Rights are subject to all of the major risks mentioned in section 3.

// d. Fixed Income Securities/Bonds: are debt securities that provide a return in the form of fixed periodic payments and the eventual return of principal at maturity. Bonds can be issued either by governments (government bonds) or companies (corporate bonds). In this sense, Bonds represent a form of government or corporate borrowing. The credit risk of governments, financial organisations, corporations and generally of any Bond issuer may be rated by Credit Rating Agencies. The result of these ratings constitutes a valuable guide for investors in Bonds. Bond issues of lower credit ratings tend to offer higher coupons to compensate the investors for the higher risk they assume. Some Bonds trade on recognised stock exchanges while many trade outside regulated markets (OTC). Liquidity usually differs between various types of Bonds. Bonds are subject to credit risk where the issuer of the Bond may not be financially solvent to pay to investors’ interest or even the principal of the Bond. Interest rate risk is the risk where increases in interest rates may cause significant decrease in the market value of a fixed‐rate Bond and where decreases in interest rates may affect the reinvestment of the coupon payments of a fixed‐rate Bond. When interest rates increase, a Bond issued previously carrying lower fixed rate may decrease in value. To his extend, the longer the maturity (duration) of the Bond the higher its sensitivity to changes in interest rates. When interest rates decrease, the coupon payments received from fixed‐rate Bonds are reinvested at lower interest rates while coupon payments received by investors from floating‐rate Bonds decrease.

// e. Convertible Bonds: give the holder the option to exchange the bond for a predetermined number of shares in the issuing company. When first issued, they act just like regular corporate bonds with a slightly lower interest rate. Because convertibles can be changed into stock and thus benefit from a rise in the price of the underlying stock, companies offer lower yields on convertibles. If the stock performs poorly there is no conversion and the investor’s return is below that of a nonconvertible bond.

// f. Callable Bonds: are bonds that can be redeemed by the issuer prior to their maturity. Any difference between a Bond’s call price and nominal value is the call premium. Call provisions expose investors to additional risks and are therefore issued with higher yields than comparable Bonds with no such provisions.

// g. Collective Investment Schemes: involve an arrangement that enables a number of investors to ‘pool’ their assets and have these professionally managed by an independent fund manager. Investments typically include bonds and shares of listed companies but depending on the type of the scheme, they may include broader investments such as property. The ability to liquidate certain Schemes may be limited, depending on the terms of operation and the long time period of notice required for redemption during which the value of each unit may exhibit high volatility and possibly decrease. It is possible that there is no secondary market for such Schemes and hence such an investment may be liquidated only through redemption.

// h. Hedge Funds: are aggressively managed portfolios of investments that use advanced investment strategies such as leveraged, long, short and derivative positions in both domestic and international markets with the goal of generating high returns (either in an absolute sense or over a specified market benchmark). Hedge funds are considered a riskier investment than traditional funds and are suitable for more experienced investors, since they are not regulated and lack transparency. They usually invest in risky or illiquid securities and although they target absolute returns, if they fail to manage risk, they may realise significant losses. Beyond the liquidity risk, Hedge Funds have the ability to leverage which means that a relative small fluctuation in the price of the underlying security may lead to a disproportionately larger fluctuation, favourable or unfavourable, to the value of the investment.

// i. Exchange Traded Funds (ETFs): are securities that track an index, a commodity or a basket of assets like an index fund, but trade like a stock on an exchange. ETFs experience price changes throughout the day as they are bought and sold. Investment in ETFs expose investors to the same risks as the underlying securities but to a significantly lower degree due to the diversification of investments.

// j. Money Market Instruments: are usually debt securities which mature in one year or less (Treasury Bills) and which are usually traded in local money markets. Risks related to this type of instruments are the liquidity risk, interest rate risk and credit spread risk.

// k. Futures: are financial derivative contracts obligating the buyer to purchase an asset (or the seller to sell an asset), such as a physical commodity or a financial instrument, at a predetermined future date and price. Futures contracts detail the quality and quantity of the underlying asset; they are standardized to facilitate trading on a futures exchange. Some futures contracts may call for physical delivery of the asset, while others are settled in cash. The futures markets are characterized by the ability to use very high leverage relative to stock markets. Therefore, a relatively small fluctuation in the price of the underlying asset may lead to a disproportionately larger fluctuation, favourable or unfavourable, to the price of the future.

// l. Options: are financial derivatives that represent a contract sold by one party (option writer) to another party (option holder) and trade on exchanges or Over the Counter (OTC). The contract offers the buyer the right, but not the obligation, to buy (call) or sell (put) a security or other financial asset at an agreed‐upon price (the strike price) during a certain period of time or on a specific date (exercise date). Their value is derived from the market value of the underlying asset (shares, currencies, interest rates, commodities, financial indices or any combination) and its volatility, the time up to maturity as well as the interest rates. Call options provide the option to buy at certain price, therefore the buyer would benefit from an appreciation of the stock’s price, while put options give the option to sell at a certain price, therefore the buyer would benefit from a depreciation of the stock’s price. Options are extremely versatile securities that can be used in many different ways. Traders use options to speculate, which is a relatively risky practice, while hedgers use options to reduce the risk of holding an asset.

// m. Swaps: are derivatives in which counterparties exchange certain benefits of one party’s financial instrument for those of the other party’s financial instrument. The benefits in question depend on the type of financial instruments involved. For example, the most common type of Swaps is Interest Rate Swap Agreements. In interest rate swaps, one contracting party agrees to pay to the other contracting party a fixed interest rate on a pre‐agreed principal amount for a specific time period. In exchange, he receives a floating interest rate on the pre‐agreed principal for the specific time period. The principal in such type of Swaps is usually not exchanged. In every settlement date, payments of the contracting parties are netted so that there is only one payment made from the contracting party with the greater liability. Interest Rate Swap Agreements are usually used to convert a floating rate loan into a fixed rate one or/and vice versa. Another common type of Swaps is Currency Swap Agreements where the contracting parties exchange a specific amount in different currencies for a specific time period. In Currency Swap Agreements, there is an exchange of principal both at the inception and termination of the agreement, while the payments between the two contracting parties at the settlement dates are not netted since they are in different currencies. In such Agreements, there is no foreign exchange risk since the exchange rate is determined at the inception of the agreement. Depending on whether the investor wishes to be hedged against a possible rise or fall in the prices of the related commodity, he takes the appropriate “position” in the swap agreement (that is to pay a fixed or floating price). Even though no initial premium is required, in case the market “moves” against the investor then he may be required to pay the amount corresponding to the difference owed. Swaps include both credit and interest rate risk. Currency Swaps entail greater credit risk than Interest Rate Swaps due to the exchange of principal both at the inception and termination of the agreement as well as the payments from both parties at every settlement date.

// n. Contracts for Differences: are contracts between two parties, typically described as “buyer” and “seller”, stipulating that the seller will pay to the buyer the difference between the current value of an asset and its value at contract time. (If the difference is negative, then the buyer pays instead to the seller.) In effect CFDs are financial derivatives that allow investors to take advantage of prices moving up (long positions) or prices moving down (short positions) on underlying financial instruments and are often used to speculate on those markets. For example, when applied to equities, such a contract is an equity derivative that allows investors to speculate on share price movements, without the need for ownership of the underlying shares. A Contract for Differences entails a high degree of risk because of the leverage involved. A relatively small fluctuation in the price of the underlying asset may lead to a proportionately larger fluctuation in the value of the investment.

// ## Investment Risks in relation to CFDs

// a. Investing in CFDs options is speculative and involves an extremely high risk. The Client acknowledges that he fully understands that minor differences in market prices may occur in ultra‐short time periods and may cause high profits or losses in relation to the CFDs acquired be the Client, as high as total loss of the Client’s entire investment, all in short time period. Furthermore, the Client acknowledges that he fully understands that there is no existing method that can assure profits from transactions in CFDs. It is the Client’s responsibility to consider whether CFDs trading is suitable to the Client’s financial position and investment objectives. If the Client does not thoroughly understand the risks involved in CFDs trading, the Client is hereby encouraged not to utilize or stop utilizing the Company’s services.

// b. By registering to the Global Investments web site or any other website that the Company uses to offer its services, and carrying out a transaction, the Client hereby acknowledges and approves the following:

// The type of Transactions offered may be considered special risk transactions and carrying them out might involve high level of risk.
// Client has full information and knowledge regarding CFDs trading and the risks involved. Transactions in general and CFDs Transactions in particular. Carrying out Transactions is at Client’s sole discretion and Client hereby undertakes the risks involved in such Transactions.
// In the event of purchasing CFDs, the Client might expose himself to considerable loss of the invested money or even to total loss of the Client’s entire investment.
// The Client acknowledges that an investment may cause substantial loss.

// c. The Client is solely responsible to ascertain whether such transactions are suitable taking into consideration his financial status and personal circumstances. It is highly recommended that the Client consult with experts before trading CFDs.
// `;
